### ISSUE TITLE
Simple database for persistence

### ISSUE THREAD

**Issue by seemir** [seemir/mydrive#21]
**Task for completion of this issue**
- [ ] Setup database (e.g. Google BigQuery ...)
- [ ] Test database (testing connection and persistence)
- [ ] Basic security feature, i.e. setup authentication for persistence
