### ISSUE TITLE
Pricing engine

### ISSUE THREAD

**Issue by seemir** [seemir/mydrive#27]
**Task description**

NB: Back-end task

- [ ] Research possible pricing engines used in the market
- [ ] Dynamic pricing, i.e. prices changes after season, time-of-day etc.
- [ ] Factors used in pricing rides, i.e. how much, which factors, etc.
- [ ] Build simple prototype of a working pricing engine
